GET http://localhost:8080


###
GET http://localhost:8080/users


###
GET http://localhost:8080/products

###
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "Halima"
   
}

###
GET http://localhost:8080/products

###
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "label": "TV Sumsung"
   
}

###
PUT http://localhost:8080/products/620f9b68251e72a7d5f6655f HTTP/1.1
content-type: application/json

{
    "label": "TV Sumsung",
    "color":"Metalic",
    "stock":3500
   
}

###
DELETE http://localhost:8080/products/622b2e2bcad692e53829300f HTTP/1.1



###
GET http://localhost:8080/ordres

###
POST http://localhost:8080/ordres HTTP/1.1
content-type: application/json

{
    "date": "lundi"
   
}